FROM python:3.10-slim-buster

COPY . app/

RUN pip install -r app/requirements.txt

WORKDIR app/

EXPOSE 8080

CMD ["uvicorn", "preview.main:app", "--host", "0.0.0.0", "--port", "8080", "--workers", "3"]